FuelLabs/fuelup

- fuelup-init.sh
Closes #18 
Script should warn users of the former location of binaries in .cargo/bin.
> check cargo installations before download happens

- fuelup-init.sh
Remove `-v` from the script to stop the extraction output from showing when running the script.
```
❯ curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/FuelLabs/fuelup/master/fuelup-init.sh | sh -s install
x fuelup-0.1.0-x86_64-apple-darwin/ <-- removes this
x fuelup-0.1.0-x86_64-apple-darwin/fuelup <-- removes this
Downloading the Forc toolchain
...
```
> Remove verbose option from tar

- fuelup-init.sh
Add a simple message to let users know that `fuelup` has been installed and that they can use `fuelup install` to fetch the latest binaries
> Add fuelup installation message at the end

- .github/workflows/gh-pages-init.yml
- README.md
I ran this in CI before force-pushing to clean up the very ugly history 😂
You can find the file here! https://github.com/FuelLabs/fuelup/tree/gh-pages, and the command in the readme works as of this PR:
```sh
curl --proto '=https' --tlsv1.2 -sSf https://fuellabs.github.io/fuelup/fuelup-init.sh
```
> Add CI to publish `fuelup-init.sh`

- .github/scripts/verify_tag.sh
- .github/workflows/ci.yml
- Cargo.toml
Adds 2 jobs:
1. toml linter to make sure the toml is formatted correctly.
2. version checker on publish. When publishing a release, will make sure the `version` in the manifest file matches the release version.
> Add lint and publish check CI jobs.

- fuelup-init.sh
Small fix to the naming of `_arch` and `_cputype` within `get_architecture`.
> fix: _arch -> _cputype naming

- fuelup-init.sh
Closes #52 
We use a combination of `grep` and `cut` instead of `jq`.
`"tag_name": "v0.1.2"`
The above is the output of the grep, then:
`cut -d "\"" -f4 | cut -c 2-`
this splits the above string with the `"` delimiter, getting the `v0.1.2` portion and cutting off the `v`
This may not also be the ideal way, but it's one solution as well, unless the solution described in the issue is preferred.
> replace jq with cut

- fuelup-init.sh
Closes #44 
- Add `_fuelup_version` to the info printed, so that users can check versioning at the release page
- Clearer err message so that users know what went wrong and where to check instead of just 'unsupported arch' -> actually, in the case of 'unsupported arch', that check should've failed at `get_architecture` already
- also removed the `$` matching in `grep` - i'm not sure why matching `$` didn't work on my machine, but matching `404` should be sufficient either way since there would be nowhere else in the message that should have a `404`
> Update err message to handle failed download

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/download.rs
Should close #2 for good, because testing is the only missing step.
- bootstrapping with a simple test just so we can get a test CI up and running.
- don't think other areas of the code are valid for testing now, perhaps we might want a more comprehensive test suite (i like cargo's one more than rustup's) once we get more commands up and running
> bootstrap ci tests

- fuelup-init.sh
Addresses an issue in https://github.com/FuelLabs/sway-applications/pull/86
We do not actually use `need_tty` in fuelup since `fuelup` works slightly differently from `rustup`. 
In `rustup` the installer `rustup-init` is the one asking to prompt to install `rustup` and other components, but in our script at the moment we are installing `fuelup` directly and `fuelup` itself does not prompt users, and only act as a regular clap app.
After this is merged we should release v0.1.3 so that the sway-applications can use the updated curl script which supplies `--no-modify-path` to skip the prompt:
```sh
curl --proto '=https' --tlsv1.2 -sSf https://fuellabs.github.io/fuelup/fuelup-init.sh | sh -s -- --no-modify-path
```
> remove need_tty

- README.md
- remove `install` as an arg since we call it by default within `fuelup-init` now.
- also added instruction for `--no-modify-path`
> update README with updated instructions

- fuelup-init.sh
Instruction needs to be updated now since `fuelup install` is now `fuelup toolchain install latest`.
> Update post-installation instructions

- .github/workflows/index-versions.yml
The script within this repo and my personal repo lived in a different place - as a result the CI for `fuelup` is failing because I didn't amend it prior to making PR #75
> fix script location

- .github/workflows/ci.yml
- fuelup-init.sh
Fixes https://github.com/FuelLabs/action-fuel-toolchain/pull/30
Args to the executable have to be separated instead of being passed as a single, whitespace-separated string.
> correctly pass args to fuelup

- Cargo.lock
- Cargo.toml
- Should fix issues with https://github.com/FuelLabs/action-fuel-toolchain/pull/30 not passing CI.
> bump 0.2.1

- fuelup-init.sh
Missing 'v' when linking to the release page since `_fuelup_version` in the script does not contain 'v':
wrong link (old):
https://github.com/FuelLabs/fuelup/releases/0.2.1
new:
https://github.com/FuelLabs/fuelup/releases/v0.2.1
> add missing 'v' to release link

- .github/workflows/ci.yml
- .github/workflows/scripts/verify_tag.sh
New PR in place of https://github.com/FuelLabs/fuelup/pull/93 since there was a CI error with a dangling `check-fuelup-init` check.
edit: seems like trying to re-open this didn't work - perhaps it doesn't matter since the old check is outdated anyway, just seems like an annoyance that happens when you edit step names.
> include .github/workflows/scripts dir in shfmt and shellcheck CI checks

- Cargo.toml
- src/ops/fuelup_self.rs
Fixes #96
`fuelup` should remove itself (unlink) before trying to download a new version. ~We will temporarily copy this as a backup in case download fails - in which case we copy the temp `fuelup` back.~
Updated with @mitchmindtree 's suggestion:
1. Create a tempdir `fuelup_new_dir` and fetch new fuelup to this dir. At this point, if download fails, do nothing else so old fuelup remains.
2. Upon success, if old fuelup already exists, rename old fuelup to `fuelup-backup`.
3. Finally, copy the new fuelup within `fuelup_new_dir` into the `bin` directory.
4. If the above step somehow fails, rename `fuelup-backup` back into the `fuelup`. If this also somehow fails, we recommend to reinstall via the `fuelup-init` script.
5. We do not need to clean up the download since we're using …
> Fix fuelup self update

- .github/workflows/ci.yml
- .github/workflows/scripts/verify_tag.sh
Fixes #88 
The step that runs `fuelup-init` to check for installation of fuelup should be run at all times, but handled differently:
1) During normal CI checks: it's ok to run it directly within `check-scripts`.
2) During releases: `fuelup-init` has to wait for releases to finish building before attempting to download the `fuelup` binary.
Note that this does not prevent releases from being uploaded if there's an error with installing fuelup-init, but only notifies.
> Separate CI step that checks fuelup-init

- .github/workflows/gh-pages-meta.yml
- fuelup-init.sh
Closes #102
Related #58, #43 
Reduces dependence on GitHub API by querying the published `fuelup-version` instead of querying the latest tag endpoint of GitHub API, since we [publish the version](https://github.com/FuelLabs/fuelup/blob/gh-pages/fuelup-version) already. We still fallback to querying the api endpoint in case curl-ing `fuelup-version` fails.
We also trim the 'v' from the published version within the workflow so that it works nicely with our script.
Note that this change means installing via `fuelup-init` on **master** will break until a new version is published. This should not affect `fuelup-init` that is published onto gh-pages though (which means it should be fine for general public)
> curl fuelup-version instead of github api

- .github/workflows/test-toolchain-compatibility.yml
`index-versions` job requires both `always()` and the skip check to run, otherwise it is always skipped despite tests successfully running. (as seen in the [actions page](https://github.com/FuelLabs/fuelup/actions))
> add always() condition to workflow

- .github/workflows/test-toolchain-compatibility.yml
Current channel has published `fuel-core` at `0.9.6` despite failing tests, because of a missing `^` in the regex matching done that doesn't exclude the files marked as `incompatible`.
To confirm:
```console
$ touch incompatible
$ touch compatible
$ ls -1 | grep "compatible*"
compatible
incompatible
$ ls -1 | grep "^compatible*"
compatible
```
Also removed the `*` from the comment.
> add '^' to correctly match compatible files only while indexing versions

- Cargo.lock
- Cargo.toml
Should fix the CI issues related to the change within https://github.com/FuelLabs/fuelup/pull/103.
> Bump v0.2.3

- scripts/compare-versions/src/main.rs
We should only re-generate the channel toml if we encounter a `404` error. If we encounter some other forms of error, we should retry at the next scheduled run of the CI check.
> compare-versions: handle 404 error vs other unexpected errors differently

- README.md
- fuelup-init.sh
_Reopened because of messed up commit tree in #135_
Small update to fuelup-init to support https://github.com/FuelLabs/action-fuel-toolchain/pull/67
Since within the action we may not always want the latest toolchain, the `--skip-toolchain-installation` option allows the action to install fuelup without installing the latest toolchain. For the convenience of general users, the default behavior should still be to install the latest toolchain.
> add `--skip-toolchain installation` to `fuelup-init`

- tests/commands.rs
- tests/testcfg.rs
Some inconsistencies in the tests due to bumping the version of `fuelup` that wasn't considered before.
1) we assert `success()` status in the `fuelup_check` now instead of the exact version string.
2) remove the `fuelup` version string check from the toolchain installation test.
> fix integration tests

- src/ops/fuelup_toolchain/new.rs
Previously `fuelup toolchain new` was trying to do `fs::read_dir()` to check for duplicate toolchains before attempting to create a new one within `/toolchains`. This led to the CI [failing](https://github.com/FuelLabs/sway-applications/runs/7917369437?check_suite_focus=true#step:8:29) if the toolchains directory did not exist to begin with (which is the case for GitHub runners).
> Check `toolchain_dir.is_dir()` before attempting to read dir

- src/ops/fuelup_check.rs
Fixes #150 
Previously `fuelup check` assumes that you would never be able to download a version greater than what's published on a channel. In the upgrade from `fuelup v0.2` to `fuelup v0.3`, there were some users that upgraded `fuel-core` to `v0.10.1`, while the channel still has `v0.9.8` published (due to failing compatibility tests). This resulted in `fuelup check` showing that there's an update available from the more recent version to the older version.
This PR handles the above issue by:
1) Explicitly telling the user that the newer version is 'unstable', and the older version is 'recommended', though this is an edge case that won't happen unless the user manually moved a newer binary into the toolchain (since `fuelup check` only checks official toolchains).
2) There's also some …
> better handling of 'fuelup check' downgrade behaviour

- src/ops/fuelup_check.rs
Closes #145 
Small update to `fuelup check --verbose` to correctly display `forc-run` and `forc-deploy` as the same package `forc-client`.
> forc client check

- src/ops/fuelup_toolchain/install.rs
https://github.com/FuelLabs/fuelup/commit/54772294712f658255de44751e74e23aa51acc56
This was an unintended change that caused `toolchain install` to look for `forc-lsp` - not sure how I didn't catch this but seems like this was accidentally updated. 
Should be immediately followed up with a new patch release since this is an urgent bug fix.
> Fix `toolchain install` command

- Cargo.lock
- Cargo.toml
Contains bugfixes and a change to `fuelup check` to more appropriate nest `forc-deploy` and `forc-run` under `forc-client`:
> Bump v0.3.3

- Cargo.lock
- Cargo.toml
Depends on:
bumping minor version number because of introduction of new command `fuelup show`.
> bump 0.4.0

- .github/workflows/scripts/index-versions.sh
This updates the 'Publish nightly channel' workflow to publish the new URLs to the nightly binaries, which now include the semver inside their names. 
Example:
Instead of `fuel-core-nightly-2022-09-02`, it will now be `fuel-core-0.10.1-nightly-2022-09-02`.
Including the semver is better than not including it, since it would dispel confusion as to which X official release that a Y nightly release was last tagged to.
You can check it out live on gh-pages branch: https://github.com/FuelLabs/fuelup/blob/gh-pages/channel-fuel-nightly.toml. Copy+paste the URL into your browser to try downloading one of the bins
> nightly ci include semver

- Cargo.lock
- Cargo.toml
- src/channel.rs
- src/commands/default.rs
- src/config.rs
- src/constants.rs
- src/download.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_component/add.rs
- src/ops/fuelup_component/remove.rs
- src/ops/fuelup_self.rs
- src/ops/fuelup_show.rs
- src/ops/fuelup_toolchain/install.rs
- src/ops/fuelup_toolchain/new.rs
- src/ops/fuelup_toolchain/uninstall.rs
- src/path.rs
- src/proxy_cli.rs
- src/target_triple.rs
- src/toolchain.rs
- tests/commands.rs
- tests/testcfg.rs
Closes #159
Allows for the command `fuelup toolchain install nightly` which sources the channel TOML from gh-pages ([example](https://github.com/FuelLabs/fuelup/blob/b0daef81746066a7c507e784eedad3f0bfc18484/channel-fuel-nightly.toml)) and downloads from the links there.
Note that this does not yet allow for specifying dates or targets, even though some of the infra code that allows for it is in this PR.
In order to support nightly, there were some refactoring that had to be done:
-  `Package` struct now takes version as a `String` instead of a `Version`. This is because nightly versions are semver versions postfixed with `-nightly` and the date at the back. `fuelup check` will use this date to check for updates.
- We used to download the channel TOMLs as temporary files, but this PR will …
> nightly support

- src/ops/fuelup_show.rs
Follow up to #167 
Fixs `fuelup show` not showing dates in nightly.
Example:
> show dates for `fuelup show` in nightly

- Cargo.lock
- Cargo.toml
Includes changes to support installing the `nightly` toolchain.
Depends on:
> bump v0.5.0

- src/component.rs
- src/main.rs
- src/proxy_cli.rs
I relooked at some code in anticipation of #163 and #162 and found some incorrect and perhaps redundant code here. 
- The if branch within `proxy_cli.rs` was never called. `component::SUPPORTED_PLUGINS.contains(&cmd_args[0].to_str())` always evaluated to false, since the `cmd_args` was not processed to form a plugin prior to the condition check
- Calling `forc deploy`, for example, used to call `forc` first. before evaluating to `forc-deploy` - so things actually still worked, but both binaries were being called.
Technically, calling `direct_proxy` is good enough since plugins automatically resolve to their intended path eg. calling `forc deploy` will evaluate `forc` with `deploy` as an arg but `fuelup` knows to call `forc-deploy`. I maintained the condition check since it seems more …
> fix proxy_cli interaction; deprecate SUPPORTED_COMPONENTS

- src/toolchain.rs
closes #7 
This PR ensures that if we install `forc`, `fuelup` creates a temporary project within `.fuelup` using `tempfile` crate, executes `forc init --path` and `forc check --path` on it.
Note that this also executes the `forc` that is within the toolchain, so the right version is fetched.
To test:
1. rm -rf ~/.forc
2. checkout this branch
3. execute `cargo run component add forc`
4. Check that ~/.forc exists
5. Repeat step 1 again and execute `cargo run toolchain install latest`, check step 4 again
> install std and core libs on installing `forc`

- components.toml
- src/component.rs
- src/main.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_show.rs
- src/proxy_cli.rs
- src/toolchain.rs
- tests/commands.rs
~_WIP_~
closes #163 
- Adds `Component` and a `Plugin` abstractions to be able to read supported components and plugins from `components.toml` (which will be shared between `fuelup` usage and the CI).
- For now, this PR will only address the `fuelup` side of things - another PR will address the CI side
- In future, any components that have to be added and distributed by fuelup will have to be configured within `components.toml`. By relying on reading this TOML, fuelup will automatically know which component/plugin is supported and be able to download it.
This PR should also partially address #162 - the hope is to be able to specify a new component or plugin in this TOML and have `fuelup` and the CI automatically detect them.
> components toml

- .github/workflows/scripts/append_package_to_channel.sh
- src/channel.rs
- tests/channel-fuel-nightly-example.toml
Closes #190 
The updated CI workflow in `sway-nightly-binaries` now append build metadata onto the version using [`cargo set-version`](https://github.com/killercup/cargo-edit#cargo-set-version).
Example version with build metadata:
`0.24.3+nightly.20220915-abcdefg`
This way, we can have the date/hash of the binaries within the build metadata to properly support some functions of fuelup (eg. `fuelup show`, `fuelup check`), and in future, when we allow users to install specific dated versions of nightly built components, instead of having to have an ugly pre-compile build script in each crate that we plan to distribute as a clap app, eg. https://github.com/FuelLabs/sway/pull/2772 and https://github.com/FuelLabs/fuel-core/pull/621
> update `nightly` publishing script to support build metadata

- src/channel.rs
- src/download.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_component/add.rs
With updates to nightlies showing dates and hashes within the build metadata, there isn't a need for `PackageVersion` anymore, and we can compare versions solely based on itself:
> deprecate package version

- .github/workflows/scripts/append_package_to_channel.sh
after #189, date format for nightlies is no longer `YYYY-MM-DD` but `YYYYMMDD`. Missed this change in the script.
> fix: date format when publishing

- Cargo.lock
- Cargo.toml
key updates:
* fix proxy_cli interaction; deprecate SUPPORTED_COMPONENTS by @bingcicle in https://github.com/FuelLabs/fuelup/pull/178
* install std and core libs on installing `forc` by @bingcicle in https://github.com/FuelLabs/fuelup/pull/183
* feat: auto detect http proxy setting. by @calldata in https://github.com/FuelLabs/fuelup/pull/187
* components toml by @bingcicle in https://github.com/FuelLabs/fuelup/pull/181
* deprecate package version by @bingcicle in https://github.com/FuelLabs/fuelup/pull/188
> bump v0.6.0

- .github/workflows/publish-nightly-channel.yml
- .github/workflows/scripts/append_package_to_channel.sh
- .github/workflows/test-toolchain-compatibility.yml
Closes #185 
Add `forc-client` to channel within the CI.
Note that in the `latest` channel, we're hardcoding versions for now. 
We probably want the same `forc-client` that is used to run tests here, since `forc-client` is fetched as a dep in the tests. However, forc-client version is also fixed there. Perhaps we also need some sort of detection mechanism to run tests everytime a new forc-client is released.
> ci: publish forc-client in CI

- src/ops/fuelup_show.rs
prior to the update to use build metadata instead we had to use a very ugly way to do `fuelup show` - which is to compare the downloaded channel instead. Instead, this time, we execute the actual binary's `--version` command, as we did before.
> refactor: remove usage of channels to show versions

- tests/commands.rs
- tests/testcfg.rs
fix some tests related to the recent addition of forc-client - more specifically the `component_add` test expected `forc-deploy` and `forc-run` to still come with `forc`.
> fix forc-client tests

- component/src/lib.rs
- components.toml
- src/ops/fuelup_component/add.rs
- src/toolchain.rs
Currently trying to remove `forc-client` doesn't work, since we are checking for `forc-client` to exist within the directory. This PR uses the `Components` abstraction to collect executables listed in the toml and remove them instead.
> fix: update component remove

- src/ops/fuelup_toolchain/new.rs
- tests/commands.rs
- tests/testcfg.rs
Closes #216 
As suggested by @Braqzen - currently you would have to switch toolchains upon creating one. eg:
```
fuelup toolchain new my-toolchain
fuelup default my-toolchain
fuelup component add ...
```
This PR combines the steps so that creating a new toolchain automatically sets it as the default, and you can carry on with whatever:
```
fuelup toolchain new my-toolchain (this step switches 'my-toolchain' to the default)
fuelup component add ...
```
This is one less step, and makes sense as a change since if you created a toolchain you would likely switch to it anyway.
>  custom toolchain: creating a new toolchain should set it as default

- Cargo.lock
- Cargo.toml
Includes changes to `fuelup toolchain new` as well as supports `forc-wallet`:
> release: v0.8.0

- tests/commands.rs
- tests/testcfg.rs
unblocks #220 
2 small changes:
- add `forc-wallet` to `ALL_BINS` to check for during tests.
- split the component adding tests to differentiate between specifying a version and not specifying one.
> test: add forc-wallet; other minor cleanups

- src/ops/fuelup_check.rs
Closes #228 
The previous implementation assumed that all plugin versions were tied to the version of `forc` - however this is no longer true since `forc-wallet` is a plugin and has its own versioning.
We do a check here to see if the channel contains a key with the component's name, and if it does,  we use the version within that instead.
> fix: forc-wallet version check

- src/channel.rs
- src/download.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_toolchain/install.rs
closes #230 
We do not need to save the channel as a file, but simply reading into memory will do. This way we avoid saving the channel to a tmp file to clean up later.
This avoids multiple file I/O steps as well (creating tmp dirs, tmp files, reading files).
> fix: remove usage of tmp dirs when installing toolchains

- tests/commands.rs
- tests/testcfg.rs
using `forc` to verify that certain download functionality work as intended can be a bit developer-unfriendly since the packaged `forc` binaries could change. Use `fuel-core` instead for better consistency, since we only want to verify that the bins are downloaded and extracted from the TAR file correctly.
> test: use 'fuel-core' instead of 'forc' for component_add tests

- tests/commands.rs
Similar to #233 , it is a bit developer-unfriendly to check for the exact binaries installed. Instead we'll just check that the command executed successfully, and that the correct toolchain directory is created.
> test: update toolchain installation tests

- src/channel.rs
- src/config.rs
- src/download.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_toolchain/install.rs
- src/ops/fuelup_toolchain/uninstall.rs
- src/path.rs
- src/toolchain.rs
closes #69 
unblocks #208 
- saves the sha256 hash of the channel to a file with file name of the toolchain eg. `latest-x86-apple-darwin` to a new directory, `~/.fuelup/hashes`
- we use this hash to avoid re-downloading a toolchain if it already exists.
- the hash is saved ONLY if the entire toolchain is installed (skipped if there are partial installations)
- the hash is deleted upon uninstallation of a toolchain i.e. `fuelup toolchain uninstall latest`
This unblocks #208 since we want to check for hashes before trying to update `latest` and `nightly`.
> feat: use update hashes

- src/ops/fuelup_self.rs
- src/toolchain.rs
- tests/testcfg.rs
closes #236 
closes #240 
The motivation is described within #240, and handling it this way coincidentally solves/closes #236 as well.
> refactor: update usages of tmp dir to use default OS tmp path

- Cargo.lock
closes #173 
The [v0.3.16 release of tracing-subscriber](https://github.com/tokio-rs/tracing/releases/tag/tracing-subscriber-0.3.16) replaces the unmaintained `ansi-term` with `nu-ansi-term`, a nushell fork of the original ansi-term.
> deps: bump tracing-subscriber

- src/ops/fuelup_update.rs
- src/toolchain.rs
closes #245 
- Provide a better message for `fuelup update` specifically rather than reuse what is in `fuelup toolchain install <toolchain>` by printing a summary message at the end.
- Also add a newline to `Adding component {} v{} to '{}'` to make things less clumped together in the terminal.
unchanged:
updated:
> better messages for fuelup update

- src/ops/fuelup_show.rs
- tests/commands.rs
closes #249 
Fixed output: 
Also replaced calls of `println` with `tracing::info` or `tracing::error`.
> fix: print output with fuelup show and replace `println` with  `tracing`

- Cargo.lock
- Cargo.toml
Contains a dependency bump (#247), and a QoL update that prints better messages for `fuelup update` (#246)
edit: waiting on #250 as well.
> release: v0.10.1

- src/ops/fuelup_self.rs
closes #252 
In order to make `copy` work without running into ETXTBSY, we should first unlink the binary first.
> bug: replace `rename` usage with remove+copy usage

- scripts/compare-versions/src/main.rs
- src/download.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_show.rs
Noticed that in the latest few compatibility checks, there were duplicate checks for the same versions ([example](https://github.com/FuelLabs/fuelup/actions/runs/3367112366)).  This is a result of there being 2 runs for the same tag: CI and Markdown Lint. We should filter for `name=CI` instead since both `forc` and `fuel-core` repos use that as the CI names.
> ci: filter by CI runs only

- components.toml
- tests/commands.rs
closes #251 officially
- Adds `forc-doc` to the list of executables under `forc`
- Separates `forc-explore` from `forc`.
> add forc-doc; remove forc-explore

- docs/src/concepts/components.md
- docs/src/installation/index.md
Updated the components page in the book to only list specifically only installable components, instead of listing all components (some of which are already packaged with `forc` like `forc-fmt`). This was probably the source of confusion of what is possible with `fuelup component add <component>`.
Also fixed links to forc plugins that was caused by the update here: https://github.com/FuelLabs/sway/pull/3182
> docs: better explanation for components; update forc-explore references

- src/channel.rs
- src/constants.rs
- src/toolchain.rs
channel published at: https://github.com/FuelLabs/fuelup/blob/gh-pages/channel-fuel-beta-1.toml
With this code update users can do `fuelup toolchain install beta-1`.
> feat: add beta-1 toolchain

- src/channel.rs
- src/constants.rs
- src/toolchain.rs
supports installation of `beta-2` toolchain: `fuelup toolchain install beta-2`.
> feat: beta-2 toolchain

- src/toolchain.rs
Closes #274 
Adding an invalid component currently panicks, as reported by @camiinthisthang:
```console
$ fuelup component add forc-core@0.14.1
thread 'main' panicked at 'no entry found for key', src/toolchain.rs:190:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is caused by the `has_component()` check which was checking if a component existed in the currently active toolchain before trying to add it, by doing `component[component]`. We should use `get()` instead.
> fix: has_component check

- src/config.rs
- src/ops/fuelup_check.rs
- tests/commands.rs
- tests/testcfg.rs
`fuelup check` got broken by the addition of `beta-1` and `beta-2` toolchains:
```sh
latest-x86_64-unknown-linux-gnu
forc - Up to date : 0.31.1
fuel-core - Up to date : 0.14.1
Unknown name for toolchain: beta
```
The problem was with the name parsing, which was trying for `beta` and not `beta-1`.
> fix: fuelup check

- src/download.rs
Closes #278 
This was also the solution to a somewhat related problem we had prior, related to ETXTBSY bug: https://github.com/FuelLabs/fuelup/pull/253
The solution is to unlink (`fs::remove_file`) the running executable prior to trying to do an `fs::copy`.
Noticed that there's a `dst_dir` in the next line which could be confusing - this should probably be fixed in a separate refactor PR.
> do fs::remove_file before fs::copy in case of running binaries

- .github/workflows/publish-nightly-channel.yml
- .github/workflows/test-toolchain-compatibility.yml
- ci/build-channel/src/main.rs
The `published_by` metadata was missing for a while in the [published channels](https://github.com/FuelLabs/fuelup/blob/f9a43d08d50aaba0ba716eec7da923903dddd831/channel-fuel-latest.toml), this PR fixes that as well as serves as a general cleanup to reduce reliance on shell commands and rather use the Rust script instead for greater reliability.
> refactor: rewrite sh commands into build-channel script

- Cargo.lock
- Cargo.toml
- docs/src/configuration.md
- docs/src/examples.md
- fuelup-init.sh
- src/commands/completions.rs
- src/commands/mod.rs
- src/fuelup_cli.rs
- src/ops/fuelup_completions.rs
- src/ops/mod.rs
- tests/commands.rs
Closes https://github.com/FuelLabs/fuelup/issues/291.
> feat: fuelup completions

- docs/src/SUMMARY.md
- docs/src/concepts/channels/beta-1.md
- docs/src/concepts/channels/beta-2.md
- docs/src/concepts/channels/index.md
- docs/src/concepts/toolchains.md
- src/commands/toolchain.rs
- Small fix to the help text of `fuelup toolchain install`
- add missing docs for testnet-specific toolchains.
> fix 'toolchain install' tooltip and add testnet toolchain docs

- src/ops/fuelup_check.rs
- src/ops/fuelup_component/list.rs
- src/ops/fuelup_show.rs
This was unsound code since the result of `fuel-indexer --version` is separated by more than 1 whitespace. We haven't ran into this issue so far since the other bins all have 1 whitespace separation between its version string and its bin name.
> fix: prefer .last() over .nth(1) while parsing version strings

- src/config.rs
- src/ops/fuelup_check.rs
- tests/testcfg.rs
As per title, fix some lints to do with needless borrows.
> fix clippy lints related to the new rust version

- src/ops/fuelup_show.rs
- tests/commands.rs
Closes #330 
Example, with `fuel-toolchain.toml` declaring `beta-2` as the overriding toolchain:
> feat: `fuelup show` should show the overridden toolchain

- src/ops/fuelup_default.rs
- src/toolchain.rs
- tests/commands.rs
closes #339 
So the cause of the bug was actually running `fuelup default` prior to installing any toolchain. As a result of the ordering of the code, a `settings.toml` file is generated but with no content inside, and on the next run of `fuelup default`, we always error out of the command, since `Toolchain::from_settings()` is the first fn call.
Changes:
- in `Toolchain::from_settings()` - check if `settings.toml` exists first.
- Reorder some code in `fuelup default`
- Added a line to assert that `settings.toml` isn't mistakenly created when `fuelup default` is ran on an empty setup.
There are 2 modes that `fuelup default` runs in. You can either execute:
1) `fuelup default`, or
2) `fuelup default <toolchain>`
The former prints out your current default toolchain and the latter switches …
> fix: default bug

- .github/workflows/publish-nightly-channel.yml
extra space in the shell command causing failure here https://github.com/FuelLabs/fuelup/actions/runs/3907520619/jobs/6676820728
> fix: nightly workflow

- src/settings.rs
`write_settings` assumes its parent directory exists when writing
`settings.toml` which is not guaranteed.
This results in a crash when invoking `fuelup toolchain install latest`
if there is no existing `.fuelup`
> Fix crash when `.fuelup` doesn't exist

- Cargo.lock
- Cargo.toml
Big update - support for `fuel-toolchain.toml`! Depends on the below:
Features:
Bug fixes:
> release: v0.16.0

- src/toolchain_override.rs
The error message for parsing a `fuel-toolchain.toml` should include the beta toolchains.
> fix: include beta toolchains in override error messages

- ci/build-channel/src/main.rs
hot fix for nightly CI publishing: without this check implemented in this PR the script overwrites the entries on each iteration: https://github.com/FuelLabs/fuelup/blob/gh-pages/channels/nightly/2023/01/19/channel-fuel-nightly.toml
> fix: nightly publishing overwriting

- component/src/lib.rs
- src/download.rs
- src/proxy_cli.rs
- src/store.rs
- src/toolchain.rs
closes #353 
Logic in `proxy_cli.rs` was broken - previously, installation of a toolchain worked as it did in the past, but in the new store paradigm, we have to install components to the store and then put symlinks in the toolchain directory instead. This PR implements this change.
> fix: install overridden components to store instead of to the toolchain dir

- .github/workflows/ci.yml
Failed to install the `build-channel` script prior to trying to use it in the job.
> fix(ci): missing install step in CI

- src/channel.rs
- src/download.rs
- src/file.rs
- src/fmt.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_default.rs
- src/ops/fuelup_toolchain/install.rs
- src/ops/fuelup_update.rs
- src/proxy_cli.rs
- src/target_triple.rs
- src/toolchain.rs
- tests/component.rs
- tests/default.rs
- tests/testcfg/mod.rs
- tests/toolchain.rs
fixes [`uninlined_format_args`](https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args) lint.
> clippy: fixes for 1.67

- components.toml
- tests/show.rs
> feat: add forc-tx info

- src/file.rs
- src/ops/fuelup_component/add.rs
- src/toolchain.rs
closes #329, closes #352
incidentally because `add_component()` is re-used in many commands eg. `toolchain install`, `update`, we get the nice effect of this change everywhere!
eg. `fuelup toolchain install latest` will now symlink components from store if they're already there. No need to wait to re-download components again.
> feat: `add_component` adds to store

- .github/workflows/test-toolchain-compatibility.yml
Applies the changes of https://github.com/FuelLabs/sway/pull/3961 on the compatibility checks.
Note that in the fuelup compatibility check CI, we are only interested in the e2e tests, so this PR only updates the existing e2e test targetting the FuelVM, and adds the tests for the EVM.
> ci: update toolchain compatibility tests

- .github/workflows/index-versions.yml
CI is getting some errors related to rate limit - unauthenticated requests seem to be limited to [60 an hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-personal-accounts). Updating the check to trigger hourly instead of every 30 minutes, since it probably isn't ideal to pass our token into the Rust script as a var...
https://github.com/FuelLabs/fuelup/actions/runs/4129790751/jobs/7135788603
> ci: small update to frequency of checks

- src/download.rs
- src/toolchain.rs
During the initial installation of fuelup and subsequently a toolchain, a fresh install would not have `.fuelup/bin` and also the linked binaries within that directory. We need to check for the linked binary within `.fuelup/bin` whenever we install a component, in case it was removed.
> bug: fix initial installation

- .github/workflows/test-toolchain-compatibility.yml
This is probably why the compatibility check might be failing. The `test.toml` has a dependency, hence the "failed to source dependency" error message here: https://github.com/FuelLabs/fuelup/actions/runs/4124188987/jobs/7126597387
> ci: build sway-libs

- .github/workflows/test-toolchain-compatibility.yml
related: https://github.com/FuelLabs/fuelup/pull/388 
The PR above fixes not being able to source dependency, but the [Forc.toml for the storage purity test](https://github.com/FuelLabs/sway/blob/9a00b5ab67ce67c5f525bdc332f15d6b6e06eb38/test/src/e2e_vm_tests/test_programs/should_fail/storage_clear_incorrect_purity_annotation/Forc.toml) cds an additional level up to the `sway` repo. Fixing this here instead by creating a dedicated sway repo when running e2e tests
edit: maybe this is the cause actually, instead of the build step above.
> ci: cd into s way when testing

- .github/workflows/test-toolchain-compatibility.yml
action currently fails without publishing an incompatibility file stub - we need to add the check for the failure conditions to the step that uploads the failure artifacts in the CI.
Also added failure check for std-lib-tests which was missing before :sweat:
> ci: check for failure for new tests

- README.md
Changed the README to have quick links for commonly asked questions. eg. How to add component to fuelup?
> docs: update README with developer guide links

- tests/component.rs
Closes #395
hotfix for failing CI in this PR #392
`fuel-core` has a new binary in the newest version which we should expect.
> fix: add fuel-core-keygen to expected files

- src/toolchain.rs
This might've broken on the refactor to make store work. We want to link fuelup to a fake 'fuelup' that masquerades as a component, eg. 'forc', which in turn calls the real 'forc'. The bug was a result of linking the real binary to `~/.fuelup/bin/forc`, instead of linking fuelup to `~/.fuelup/bin/forc`. Hence calling forc would always default to whatever was first installed.
> fix: link fuelup and not the binary

- docs/src/concepts/channels/beta-3.md
- docs/src/concepts/channels/index.md
This PR adds a `beta-3` entry in the Channels `index.md`. Additionally, adds a new page under Channels chapter to cover `beta-3`.
Closes #399
> Add beta-3 entry under Channels in Fuelup book

- tests/default.rs
- tests/show.rs
- tests/testcfg/mod.rs
- tests/toolchain.rs
This PR contains a bunch of minor cleanups to tests. Because these cleanups are spread across different places, will briefly explain some of the changes:
- I wrote doc comments at places where I think is necessary to get the gist of what's going on in tests (in the setup, in the `FuelupState` enum)
- Removed the `LatestAndNightlyInstalled` enum member from `FuelupState` since only 1 test uses this. We can reuse `AllInstalled` instead.
- Repurposed `LatestAndNightlyWithBetaOverride` to `LatestWithBetaOverride` just to cut down on the variable name and we don't require 2 toolchains anyway for the purpose of testing overrides.
- Created a `pub const CUSTOM_TOOLCHAIN_NAME` for tests that use and assert `my-toolchain` custom name.
- Remove `root` from `TestCfg` since it served no purpose.
> test: general cleanup

- component/src/lib.rs
- src/file.rs
- tests/show.rs
- tests/testcfg/mod.rs
closes #411
follow up to #410
When we introduced the store architecture, the test infra was not updated to reflect this, so the behaviour diverged abit, even if tests passed. Instead we just had the same setup (toolchain directory created only). 
This PR updates the test environment setup by mimicking the actual environment again. Assuming the test env is created under a directory `.tmpA3bI3`:
1. create the actual executable within the store, eg. `forc` is created in `/.tmpA3bI3/.fuelup/store/forc-0.35.3` for example.
2. link the executable to the toolchain bin directory, eg. `/.tmpA3bI3/.fuelup/toolchains/my-toolchain/bin/forc`
3. execute tests as per normal.
I also added a test as a sanity check in the case where a specific `fuels_version` file is removed.
> test: introduce store infra to test fuels_version.

- component/src/lib.rs
- components.toml
- src/channel.rs
- src/constants.rs
- src/download.rs
- src/ops/fuelup_show.rs
- src/store.rs
- tests/channel-fuel-latest-example.toml
- tests/show.rs
closes #289
This doesn't really address the issue directly because it shows the compatible `fuels` version on a component level rather than the toolchain level, which I think is probably better.
I was contemplating between dealing with this on the toolchain-level or on the component-level, and it came down to where we wanted the logic for getting the fuels version to live.
Ultimately, trying to get the fuels version means we have to unavoidably fetch it from the `Cargo.toml` directly, whether we solve it on the toolchain-level or component-level.
On the toolchain-level, we could publish the info in our channels, but that means that on a component-level we do not know what `fuels` version is compatible.
On the component-level, we could fetch the info directly on the first installation, but …
> feat: support fetching and showing fuels_version in fuelup show

- .github/workflows/index-versions.yml
- Cargo.lock
- ci/compare-versions/Cargo.toml
- ci/compare-versions/src/main.rs
- tests/expects/mod.rs
closes #377
Adds an alternative mode to `compare-versions` to check for other components other than `forc` and `fuel-core`. Modes are selected by inputting an arg after running the `compare-versions` Rust program. `compare-versions` is still ran every hour by the fuelup gh CI, and the workflow is edited to run them as appropriate.
You may either input *compatibility* or *rest*:
**compatibility**: 
runs the same check we had as always. This is run prior to the toolchain compatibility tests - no changes here.
**rest**:
runs a check that compares latest actual released versions versus latest indexed versions in our `channel-fuel-latest.toml` TOML file, and executes the build-channel script to build a new channel if there are any new versions detected.
Note that this excludes `forc` and …
> ci: index other components

- .github/workflows/index-versions.yml
CI is failing - We simply missed a check for if the file is missing. Then we ignore the rest of the steps.
> fix: do not run if no channel published

- src/file.rs
- src/proxy_cli.rs
- tests/override.rs
- tests/testcfg/mod.rs
closes #422 
The entire bug was a result of a one-line mistake:
https://github.com/FuelLabs/fuelup/blob/784edcddd8dc28b7499b4410d5c3fc8802ebe281/src/proxy_cli.rs#L74
If you look at the source code you can see that `component_name` is used to derive the path of a binary if a version was specified in an override. In the case of forc, we require this `component_name` instead of using `proc_name` as seen in the function because forc plugins are packaged together with forc - which means if we want to find  the directory that contains `forc-deploy v0.35.5`, this would be found in `forc-0.35.5`, which means we would have to use `component_name` (forc) instead of `proc_name` (forc-deploy, for example)
The bug was caused by using the `component_name` to invoke the binary instead of using the …
> fix: proxy_cli erroneously executes `forc` when forc plugins are called

- .github/workflows/test-toolchain-compatibility.yml
https://github.com/FuelLabs/sway/blob/607ac50176db8bef936f91bacf435d0ea37d041e/.github/workflows/ci.yml#L18-L19
Also switched usage of actions-rs to dtolnay/rust-toolchain.
> ci: bump versions to match sway repo ci

- src/channel.rs
- src/config.rs
- src/download.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_toolchain/install.rs
- src/ops/fuelup_toolchain/uninstall.rs
- src/ops/fuelup_update.rs
- src/toolchain.rs
Closes #418 
Prior to the 'store' model that we now use, each binary was not cached in some local location. We used basic sha256 hashes stored within .fuelup/hashes directory as a way to tell fuelup that a toolchain already exists. This is important to ensure that users don't waste time re-downloading binaries that they have already downloaded once before.
With the store model, we no longer need this since it's much faster now to re-install toolchains with duplicate binaries since they are all cached in the store. We can now get rid of this hacky way of speeding up the download process, since it's built-in to the design.
> chore: deprecate usage of hashes to check download duplication

- docs/src/concepts/how_fuelup_works.md
- Improve clarity over what fuelup-init is by adding a link
- Reword some things
> docs: reword some things; add link to fuelup-init

- .github/workflows/ci.yml
The build-channel program was changed in #392 but this part of the CI was not updated to match the new usage method.
> fix: build-channel usage within CI

- Cargo.lock
- Cargo.toml
- tests/toolchain.rs
unblocks #433
Fixes 1.69 clippy lint issues.
>  chore: bump clap and clap complete to address 1.69 clippy lint issues

- .github/workflows/index-versions.yml
We were checking for an empty $CHANNEL_TOML which will always evaluate to false.
There's also some refactoring here to combine 2 steps (the step with the issue and the step below) to make it more readable.
> ci(fix): fix missing `CHANNEL_TOML` in check.

- channel-fuel-latest.toml
- channels/latest/channel-fuel-latest-2023-07-05.toml
Seems like ci missed forc-wallet artifacts for apple_x86 and apple_arm64, this PR adds them to fix fuelup latest channel.
> fix: add missing forc-wallet entries for 2023-07-05 latest run

- channel-fuel-beta-3.toml
bumps indexer version to 0.18.4 for beta-3 network
> chore: bump fuel-indexer to 0.18.4 for beta-3 network

- channel-fuel-beta-3.toml
- This PR bumps the latest beta-3 indexer to 0.19.1.
- This is confirmed as beta3 compatible
> chore: bump beta3 indexer

- docs/src/concepts/channels.md
- src/channel.rs
- src/constants.rs
- src/toolchain.rs
Adds beta-4-rc2 support to fuelup so that people can install it via:
```console
fuelup toolchain install beta-4-rc.2
```
Unfortunately due to how fuelup parses toolchain metadata it is not straightforward to make it possible to use:
```console
fuelup toolchain install beta-4-rc-2
```
We can support it later on and change the name if necessary as this is more towards to our internal testing, I feel like timing is has a little priority rn, but happy to mark this as draft and handle that if it seems like blocker.
> feat: add `beta-4-rc-2` dist channel support

- .github/workflows/test-toolchain-compatibility.yml
- ci/compare-versions/src/main.rs
Check versions failed https://github.com/FuelLabs/fuelup/actions/runs/5883810160/job/15957285050 because we need rust version 1.70.0 or higher in CI.
> ci: use rust 1.71 in ci

- incompatible-versions/forc-0.44.1@fuel-core-0.18.3
- incompatible-versions/forc-0.44.1@fuel-core-0.19.2
- incompatible-versions/forc-0.44.1@fuel-core-0.20.3
- incompatible-versions/forc-0.44.1@fuel-core-0.20.4
Removes incorrect incompatible versions flagged due to CI rust version error.
Related to #475
> fix: remove incorrect incompatabile versions flagged by fuelup

- tests/testcfg/mod.rs
> fix: canonicalize path for tmp test directories

- channel-fuel-latest.toml
Due to a release error in forc-wallet's CI we had a faulty release which broke the latest channel. This fixes it by adding the new release manually to unblock the CI again
> fix: manually add missing forc-wallet entries

- channel-fuel-beta-4.toml
Adds beta-4 channel with following versions:
1. forc v0.45.0
2. fuel-core-* v0.20.4
3. indexder binaries v0.20.7
4. forc-explore 0.28.1
5. forc-wallet v0.3.0
> release: add beta-4 toolchain manifest

- Cargo.lock
- Cargo.toml
Waiting for:
1. https://github.com/FuelLabs/fuelup/pull/480
> chore: bump to v0.19.5

- .github/workflows/index-versions.yml
Our CI runs are failing, possible due to lack of memory/storage on ci runner. 
This fix is also applied to sway repo ci: https://github.com/FuelLabs/sway/commit/e75f14b03636bc96751a6760304a1a6d3eb5937d
> ci: use bigger image to run check-versions ci workflow

- .github/workflows/index-versions.yml
- .github/workflows/test-toolchain-compatibility.yml
This is the reusable workflow where the tests are actually run. I think that's why https://github.com/FuelLabs/fuelup/pull/488 didn't work.
Also adds a manual trigger for this job, and changes the cron to run every 6 hours.
> Use larger image in test-toolchain-compatibility.yml

- .github/workflows/test-toolchain-compatibility.yml
Apparently using github's cache with a buildjet image actually makes runs slower over time. This uses the [buildjet cache](https://buildjet.com/for-github-actions/docs/guides/migrating-to-buildjet-cache#rust) instead.
> Use buildjet cache for faster runs

- ci/compare-versions/src/main.rs
- component/src/lib.rs
- src/ops/fuelup_component/list.rs
Applies various clippy lints to unblock CI after rust version 1.73 release.
> chore: apply `clippy` lints for rust v1.73.0

- docs/src/concepts/channels.md
- src/constants.rs
Changes latest channel to point beta-4 which is the latest network. We can later on create a new channel with a different name (maybe `latest-local`?) to offer current latest channel. One other alternative is to keep publishing latest as it is but default to beta-4. I can change the PR to that approach as well according to comments.
> feat: make the latest channel point to beta-4

- Cargo.lock
- Cargo.toml
supersedes #503.
There is a breaking change: #506 so this is a minor bump as opposed to a patch release. Thus I also ran `cargo update`.
> chore: bump version to v0.20.0

- docs/src/concepts/channels.md
- src/channel.rs
- src/constants.rs
- src/toolchain.rs
closes #502.
Removes beta-4-rc and beta-4-rc2 channels from fuelup. This is a breaking change.
> chore: remove beta-4-rc* channels

- ci/build-channel/src/main.rs
closes #514.
This PR introduces support for having `-rc` in version strings for distributed components.
> feat: support `-` char in versions for distributed components in build-channel script

- Cargo.lock
- Cargo.toml
- src/fmt.rs
- src/lib.rs
- src/logging.rs
- src/main.rs
- src/ops/fuelup_check.rs
- src/ops/fuelup_component/list.rs
- src/ops/fuelup_show.rs
- src/ops/fuelup_update.rs
- src/path.rs
- tests/check.rs
- tests/default.rs
- tests/show.rs
Closes https://github.com/FuelLabs/fuelup/issues/519
This writes logs to `~/.fuelup/log` rolling over every hour. For example `~/.fuelup/log/fuelup.log.2023-11-22-00`
Since `tracing` is used for showing output to the user as well, I added a filter so that`debug` logs will only be logged to the filesystem, not shown to the user.
The PR also includes:
- Cleans up existing logs: the output shown to the user is a combination of tracing and plain `writeln`s. In order for the log file to capture everything the user is shown, we should output everything through tracing macros.
- Adds useful `debug` logs about the environment and the command that was called. It doesn't log the full PATH, because that could contain sensitive information, rather it logs whether or not the `.fuelup` directory is …
> Write logs to filesystem

- src/ops/fuelup_check.rs
- src/ops/fuelup_component/list.rs
- src/ops/fuelup_show.rs
- src/ops/fuelup_update.rs
close [#182](https://github.com/FuelLabs/fuelup/issues/182)
This PR added a function `pad_spaces(num: usize) -> String` to conveniently input the number of spaces we want.
> feat: using rust's built-in alignment to place spaces we want

- src/channel.rs
- src/constants.rs
- src/toolchain.rs
Adds beta-5 support to fuelup, once we have the toolchain toml merged as well we should make sure to point latest to it. I kept it like it so that tests would pass.
> feat: add beta-5 support

- Cargo.lock
- Cargo.toml
Bumps the version to 0.21.0. Since this is a major bump, alsa ran `cargo update`
> chore: bump version to 0.21.0

- index.html
This PR introduces an index.html file at the root of the gh-pages branch to facilitate automatic redirection to the `fuelup-init.sh` script when the root URL (https://install.fuel.network/) is accessed. This change simplifies the process for users to download and install `fuelup` by allowing a direct curl command from the root URL.
The motivation is to change the install command from 
```
curl -sSf https://install.fuel.network/fuelup-init.sh | sh
```
to this
```
curl -sSf https://fuel.network/install | sh
```
> add html redirect to install script

- channel-fuel-beta-5.toml
Bumps:
1. wallet to 0.4.3
2. forc to 0.49.2
> chore: bump beta-5 versions: wallet-cli to 0.4.3 and forc to 0.49.2

- .github/workflows/gh-pages-meta.yml
- .github/workflows/gh-pages.yml
- README.md
- docs/src/installation/index.md
Credit to @luizstacio for the idea!
Taking advantage of the fact that there was previously no index.html on this website (the page was a 404), we simply copy the installation script into `index.html`.
This change allows users to install from [https://install.fuel.network](https://install.fuel.network). I pushed the change to the gh-pages branch directly so you can test it already with:
```
curl -fsSL https://install.fuel.network/ | sh
```
I’ll make a release after this is merged to verify the gh action. Version bump: https://github.com/FuelLabs/fuelup/pull/578
> Support installing from a shorter URL

- Cargo.lock
- Cargo.toml
Will merge after https://github.com/FuelLabs/fuelup/pull/577 and make a release.
> chore: bump version to 0.21.1

- channel-fuel-beta-5.toml
Bumps fuel-core version to 0.22.1 in beta-5 channel (from 0.22.0)
> chore: bump fuel-core version to 0.22.1 in beta-5

- component/src/lib.rs
- src/download.rs
- tests/testcfg/mod.rs
Applies rust v1.77.0 clippy lints to the repo.
> chore: apply new clippy lints with rust v1.77.0

- src/download.rs
current proxy env variable only support lowercase `http_proxy`.
add other common proxy env variable, and ignore case.
> support more proxy env names

- docs/src/basics.md
- docs/src/installation/index.md
As I first run `fuelup toolchain install latest`, I failed because of network errors, and didn't find the instruction to set an http proxy to solve this problem. We should add this part IMO 😀
> doc: add fuelup http proxy setting document

- channel-fuel-beta-5.toml
bumps fuel-core version to 0.22.4 for beta-5 channel.
> chore: bump beta-5 fuel-core to 0.22.4

- src/channel.rs
- src/constants.rs
- src/toolchain.rs
adds a `preview` channel for distributing internal channels.
> feat: add preview reserved channel

- src/ops/fuelup_self.rs
Currently fuelup self update does only check for equality between the latest released version and current bin version for omitting updates. But this breaks release procedure because once fuelup version is bumped, fuelup self update tries to downgrade itself as latest released version and current version is not equal. This blocks #603
> fix: fuelup self update should not update if current bin version is higher

- Cargo.lock
- Cargo.toml
Bumps repo to 0.22.0, also ran `cargo update` as this is a major.
> chore: bump to v0.22.0

- channel-fuel-devnet.toml
Adds devnet toolchain toml file with:
1. forc-wallet 0.7.0
2. forc* 0.58.0
3. fuel-core 0.26.0
> feat: add devnet toolchain toml

- Cargo.lock
- Cargo.toml
Bumps fuelup to 0.23.0. This is a major, as #609 is breaking.
> chore: bump to v0.23.0

- src/channel.rs
- src/constants.rs
- src/toolchain.rs
Adds `testnet` reserved channel which points to `channel-fuel-testnet.toml` on gh-pages of this repo.
> feat: add `testnet` reserved channel

- Cargo.lock
- Cargo.toml
Releases v0.24.0 to get #612 released.
> chore: bump to v0.24.0

- Cargo.lock
- Cargo.toml
Bumps the version to v0.25.0, this is major one as #618 is breaking.
> chore: bump to v0.25.0

- src/commands/mod.rs
- src/commands/upgrade.rs
- src/fuelup_cli.rs
- src/ops/fuelup_upgrade.rs
- src/ops/mod.rs
- tests/upgrade.rs
Adds `fuelup upgrade` command which executes:
1. Updates fuelup itself (`fuelup self update`)
2. Switches to latest channel (`fuelup default latest`)
3. Updates fuelup channels (`fuelup update`)
> feat: add upgrade command to auto update fuelup, switch to latest and update installed channels

- src/download.rs
Closes https://github.com/FuelLabs/fuelup/issues/634
The problem is that BTreeMap index accession with `[]` doesn't return a result or option, it just panics if it's not there.
It would be good to have a lint to require us to use `get()` instead of index access, to avoid panics like this: https://github.com/FuelLabs/fuelup/issues/636
> fix: Fix panic in fuelup download

- Cargo.toml
- src/download.rs
- src/lib.rs
- src/ops/fuelup_check.rs
- src/proxy_cli.rs
- src/toolchain.rs
- src/toolchain_override.rs
Closes https://github.com/FuelLabs/fuelup/issues/636
Adds `clippy::indexing_slicing`, updates the code to remove instances of index slicing, and adds some unit tests for the functions that were significantly refactored.
> chore: Add indexing_slicing lint

- Cargo.lock
- Cargo.toml
- component/Cargo.toml
- component/src/lib.rs
- src/download.rs
- src/toolchain_override.rs
- tests/component.rs
- tests/show.rs
> Add the indoc crate to help clean up examples

- components.toml
- docs/src/concepts/components.md
- fuelup-init.sh
- tests/show.rs
- tests/testcfg/mod.rs
- tests/update.rs
[forc-explorer](https://github.com/FuelLabs/forc-explorer) has been archived so we are removing it from fuelup.
> remove forc explore

- channel-fuel-testnet.toml
follows on from the 0.30 patch @kayagokalp did in #646
> bump testnet to use fuel-core v0.31.0

- Cargo.lock
- Cargo.toml
waiting on #647
major version as #644 was breaking.
> chore: bump to v0.26.0

- channel-fuel-testnet.toml
> chore: bump testnet to use forc v0.63.3

- channel-fuel-testnet.toml
> Revert bumping testnet to use fuel-core 0.38.0 back to 0.37.1

- components.toml
- tests/testcfg/mod.rs
The `forc-client` component was still pointing to its old GItHub repository. This PR found while investigating #654 updates `forc-client` to where it lives now - the `forc-binaries` tarball release.
> Update component target tarball (#654)

- docs/src/concepts/channels.md
- docs/src/developer_guide/building_a_channel.md
- docs/src/overrides.md
- src/channel.rs
- src/commands/toolchain.rs
- src/constants.rs
- src/download.rs
- src/toolchain.rs
- src/toolchain_override.rs
- tests/check.rs
- tests/default.rs
- tests/show.rs
- tests/testcfg/mod.rs
- adds mainnet channel
- removes betas 1-5, and devnet
> feat: add mainnet channel, remove betas

- Cargo.lock
- Cargo.toml
Bumps version to 0.27.0, this is a major bump as #677 is breaking.
> chore: bump version to v0.27.0

- Cargo.lock
- Cargo.toml
- component/src/lib.rs
- src/target_triple.rs
- src/toolchain_override.rs
- tests/testcfg/mod.rs
- tests/toolchain.rs
This PR contains tests that demonstrate inconsistencies found in #654.
Once this PR is merged, the following PRs can then be updated along with removing corresponding `should_panic` test attributes:
- #665
- #666
- #667
Since #668 builds on top of the fixes in #666 and #667 and so will have conflicts and duplication, it will need to wait for the above PRs to be merged first before being mergeable.
> Add tests and highlight issues with should_panic

- src/toolchain.rs
- tests/toolchain.rs
When a proxy CLI'd command downloads a missing toolchain, multiple binary files within the downloaded distribution were being symlinked to the same one target file (thus overwriting each previous target).
This fixes an issue found while investigating #654.
> Fix incorrect binary link target

- component/src/lib.rs
When checking if a component is distributed by `forc`, we currently only look at `forc`'s direct executables. This needs to be extended to resolve components, plugins, and executables.
This fixes a few issues found while investigating #665.
> Extend finding components to plugins and executables distributed by forc

- channel-fuel-mainnet.toml
- channel-fuel-testnet.toml
- Bumps forc-wallet version to v0.11.1
> chore: bump mainnet and testnet to use forc-wallet v0.11.1

- .github/workflows/ci.yml
GitHub's actions/upload-release-assets is no longer maintained and seems to repeatedly break (e.g. SSLV3_ALERT_BAD_RECORD_MAC), so I suggest moving to a highly active and up to date runner.
> chore: swap deprecated actions/upload-release-assets to softprops/action-gh-release

- component/src/lib.rs
- components.toml
- docs/src/installation/index.md
- tests/show.rs
- tests/testcfg/mod.rs
Sway's https://github.com/FuelLabs/sway/pull/3885 added a new executable to submit transactions to the network, but it was missed in the `fuelup` repo.
> Add `forc-submit` to components.toml (sway #3875)

- docs/src/concepts/channels.md
Also removing the breaking change note as this happened a long time ago with an old version and doesn't make sense anymore.
> Update `channels.md` to reflect that the `latest` channel now points to master  instead of the testnet

- src/toolchain.rs
Somehow this list got clobbered. This resulted in a bug where `fuelup update` would not update mainnet and testnet.
> fix: update reserved names

- .github/workflows/ci.yml
- .github/workflows/publish-nightly-channel.yml
- docs/src/basics.md
- src/settings.rs
Fixing CI errors seen in https://github.com/FuelLabs/fuelup/pull/705
Makes it so we:
- use the newest nightly for codecov workflow, which requires nightly (this fixes the codecov failure)
- uses a fixed version of rust for all of the other workflows (previously it was using the only nightly version for everything)
- this fixes the clippy error
> ci: update rust version to 1.85.0

- channel-fuel-testnet.toml
```
cargo run -- channel-fuel-testnet.toml 2025-03-03 forc=0.66.7 forc-wallet=0.12.0 fuel-core=0.41.7 fuel-core-ke
ygen=0.41.7
```
When forc 0.67.0 is available, we'll update the channel again.
> chore: upgrade testnet to fuel-core 0.41.7

- .github/workflows/gh-pages-meta.yml
closes #718.
I realized we used to have a similar issue for other stuff in gh-pages. #700 and #701 is merged to fix that. This PR brings the fuelup env and key generation steps to publishing the metadata as well.
> fix: use app-key and fuelup-env for publishing last version metadata

- .gitignore
- ci/update-compiler-explorer/src/git.rs
- ci/update-compiler-explorer/src/main.rs
The `update-compiler-explorer` script has been [failing in CI](https://github.com/FuelLabs/fuelup/actions/runs/14788525241/job/41686960842#step:5:3637) due to issues primarily related to git authentication and repository handling within the GitHub Actions environment. This PR addresses these problems to ensure the script can run reliably.
*   **Git Authentication:**
*   Modified `git::clone_fork` and `git::git_push_with_retry` to use the `GITHUB_TOKEN` for authenticating `git clone` and `git push` operations via HTTPS. This resolves errors like `fatal: could not read Username for 'https://github.com': No such device or address`.
*   The `GITHUB_TOKEN` is now passed from `main.rs` through to the relevant git functions.
*   **Upstream Branch Resolution:**
*   Corrected the `git reset …
> Fix: Resolve git auth and upstream errors in update-compiler-explorer script

- components.toml
- docs/src/installation/index.md
- tests/show.rs
- tests/testcfg/mod.rs
Adds the `forc-publish` command to `fuelup` components list.
> add: forc-publish binary

- .github/workflows/update-compiler-explorer.yml
- ci/update-compiler-explorer/src/git.rs
Looks like the update-compiler-explorer action [failed again](https://github.com/FuelLabs/fuelup/actions/runs/15128708066/job/42525476684).
This PR aims to provide clearer error messages so we can debug the issue further and make the script more resilient.
To facilitate focused debugging of the core script logic, the automatic triggering of this workflow upon changes to `channel-fuel-mainnet.toml` (and the associated `check-forc-version` job) has been temporarily disabled. The workflow will now only run when manually dispatched.
> Fix: Improve git error handling in update-compiler-explorer script

- component/src/lib.rs
- components.toml
- docs/src/installation/index.md
- tests/show.rs
- tests/testcfg/mod.rs
Adds `forc-call` command to fuelup components list.
closes https://github.com/FuelLabs/fuelup/issues/727.
> feat: add forc-call binary

- tests/testcfg/mod.rs
When a new tool is added to the nightly channels, it becomes hard to test things because the override channel does not contain the tested binary.
To make this process easier I changed the nightly date we pin-to dynamic and point to yesterday anytime the tests are executed. This way if the new binary added to the nightly it will be available in the tests in the next day.
This was why #728 was blocked for some time.
> tests: actually point to yesterday for nightly overrides

- .github/workflows/update-channel.yml
- ci/build-channel/src/main.rs
This pull request introduces a new GitHub Actions workflow for managing channel updates and improves the parsing logic in the `build-channel` script to handle version strings with a 'v' prefix.
The changes streamline the automation process for updating channels and ensure better handling of version inputs.
* [`.github/workflows/update-channel.yml`](diffhunk://#diff-2b36e3fdc20feb042dd75ef02e47bfc426d509b17922068e1097a6e48d266b0fR1-R170): Added a new GitHub Actions workflow to automate the process of updating channels (`devnet`, `mainnet`, `nightly`, `preview`, `testnet`).
* The workflow includes steps for setting up the environment, building the channel, committing changes, and creating or updating pull requests. It also supports optional version inputs for `forc`, `forc-wallet`, …
> trigger toolchain updates to gh-pages branch

- ci/update-compiler-explorer/src/git.rs
Fixes the upstream repository URL mapping in the `update-compiler-explorer` script.
The script was incorrectly trying to fetch from `https://github.com/compiler-explorer/compiler-explorer-infra.git` (which doesn't exist) instead of the actual upstream `https://github.com/compiler-explorer/infra.git`.
> Fix: Correct upstream repository mapping in update-compiler-explorer script

- ci/update-compiler-explorer/src/git.rs
This removes the workflow files from git's index (but keeps them on disk) so they won't be included in any commits or pushes.
> Remove workflow files from git tracking to avoid permission issues

- ci/update-compiler-explorer/src/main.rs
we forgot to write the result of the changes back to disk so git could find the changes to commit
See [this run](https://github.com/FuelLabs/fuelup/actions/runs/15695115990/job/44218614156).
```
HEAD is now at c702bed51 Prefer Release builds for MSVC compilers in ceconan (#7760)
Switched to a new branch 'update-sway-0.68.7'
Updated for Sway version 0.68.7
On branch update-sway-0.68.7
nothing to commit, working tree clean
No changes to commit for version 0.68.7.
```
> write updated content back to disk so there and changes to commit

- .github/workflows/update-compiler-explorer.yml
Use a Personal Access Token (PAT) instead of a GitHub App token to resolve permission errors when creating pull requests to update Compiler Explorer.
> Use PAT for Compiler Explorer updates

- docs/src/basics.md
Description:  
This pull request corrects a typo in the "Supported proxy environment variables" heading in basics.md, ensuring accurate and professional documentation formatting.
> Fix Typo in Proxy Environment Variables Heading

- tests/show.rs
nothing fancy just fixed a typo in variable name
> Fix Typo in Variable Name

- docs/src/examples.md
- docs/src/overrides.md
- src/commands/toolchain.rs
- src/ops/fuelup_toolchain/export.rs
- src/ops/fuelup_toolchain/mod.rs
- tests/toolchain.rs
Adds `fuelup toolchain export` command to generate shareable toolchain configurations.
- Exports active or specified toolchain to `fuel-toolchain.toml`
- Auto-detects installed components with versions
- Supports custom output paths with `--output/-o` flag
- Handles latest/nightly channels with date formatting for validity
- Includes `--force` flag to overwrite existing files
```sh
fuelup toolchain export                   # Export active toolchain
fuelup toolchain export my-custom         # Export specific toolchain
fuelup toolchain export -o backup.toml    # Export to custom path
```
Closes #322
Supersedes #526
>   feat(toolchain): Add export command to generate fuel-toolchain.toml

- .github/workflows/scripts/verify_tag.sh
```markdown
- Corrected typo in `.github/workflows/scripts/verify_tag.sh`
- Changed `preceeding` to `preceding` in line 26 comment
```
> Fix typo in verify_tag.sh

- .github/workflows/ci.yml
- allow the coverage workflow to write issue comments when GitHub grants the token permission
- skip the comment update when the PR comes from a forked repository so the step stops erroring
> Avoid coverage comment failures on forked PRs
