FuelLabs/fuelup

Cargo.toml, src/download.rs
=> deprecate curl in favour of ureq

fuelup-init.sh
Previously, `fuelup-init.sh` would only work with `bash`. Now it works with `sh`.
Also fixed some bugs so it actually works now.
=> Fix fuelup-init.sh and make it sh-compliant.

fuelup-init.sh
=> update cut command

Cargo.lock, Cargo.toml
=> Bump to v0.1.2

fuelup-init.sh
Closes #53 
Ran this command:
```sh
shfmt -i 2 -ci -w fuelup-init.sh
```
=> Fix formatting for `fuelup-init.sh`

.github/workflows/ci.yml, fuelup-init.sh
Closes #31 
Testing CI actions for .sh files
There are:
https://github.com/luizm/action-sh-checker
and https://github.com/ludeeus/action-shellcheck
Trying out the first one because it seems like there's fmt support(?)
=> Try sh ci actions

Cargo.lock, Cargo.toml
=> Bump to v0.1.3.

.github/workflows/index-versions.yml, .github/workflows/scripts/index-versions.sh, .github/workflows/test-toolchain-compatibility.yml, CHANNELS.md, README.md, scripts/compare-versions/Cargo.toml, scripts/compare-versions/src/main.rs
__WIP - Opening PR for visibility__
Closes #83 
__Note when reviewing:__ I've changed the workflow to trigger on `push` into this branch, instead of `schedule`. This is only for the purpose of testing the workflow for now, and it should be changed back to a scheduled cron job prior to merging.
_Please see details on the design within the comment [here](https://github.com/FuelLabs/fuelup/pull/95#issuecomment-1173928649)_
_Comment on how to review [here](https://github.com/FuelLabs/fuelup/pull/95#issuecomment-1177211625)_
=> Test toolchain compatibility

.github/workflows/index-versions.yml
Accidentally uncommented the comment while merging #95
=> Fix uncommented comment within workflow

src/ops/fuelup_check.rs
Small refactor to make fuelup_check.rs more readable - no logical changes here, just moving things around.
=> fuelup check refactor

.github/ISSUE_TEMPLATE/blank_issue.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement_request.yml
=> add issue templates

src/settings.rs, tests/settings-example.toml
closes #115 
- Implements serialization/de-serialization for `Settings`
- Added tests for reading/writing `Settings`
=> `Settings` serialization/deserialization

src/component.rs, tests/commands.rs
=> Update supported components

README.md
=> Fix link to fuelup and sway books in README

Cargo.lock, Cargo.toml
=> Bump v0.3.2

.github/workflows/markdown-lint.yml, .markdownlint.yaml, docs/src/concepts/channels/latest.md, docs/src/concepts/index.md, docs/src/installation/index.md
=> Add markdown lint

README.md, docs/src/concepts/components.md, docs/src/examples.md
some documentation cleanup to describe things more accurately in `README.md` with links to the book + adding info about `fuelup show`.
=> clean up docs

tests/commands.rs, tests/testcfg.rs
Include `forc-client` bins in the tests.
=> update tests for `forc-client` inclusion

docs/src/SUMMARY.md, docs/src/concepts/channels/index.md, docs/src/concepts/channels/nightly.md
=> Add nightly channel page to fuelup book

docs/src/installation/index.md
- add forc-client to description in the Installation page
- add check for `forc-deploy` and `forc-run`
=> docs: update quickstart

Cargo.lock, Cargo.toml
=> release: bump 0.7.1

docs/src/concepts/components.md, docs/src/concepts/toolchains.md, docs/src/examples.md
- Update docs with `forc-wallet` mentions.
- Mention `nightly` as one of the official toolchains.
- remove the `default` step within `toolchains.md` since creating a new toolchain now switches to it as default (v0.8)
=> docs: various minor updates

components.toml
=> remove publish = true for `forc-client`

src/commands/toolchain.rs
=> update help message for toolchain installation

Cargo.lock, Cargo.toml
=> release: v0.10.0

Cargo.lock, Cargo.toml
=> release: v0.10.2

src/commands/toolchain.rs
Add `beta-1` and updated description of `toolchain new` command.
=> fix: help for toolchain install

Cargo.lock, Cargo.toml
Contains bug fixes and code quality related changes.
=> bump v0.11.1

Cargo.lock, Cargo.toml
=> release: v0.12.0

Cargo.lock, Cargo.toml
Contains 2 critical bug fixes that affects the beta toolchains:
=> release: v0.12.1

Cargo.lock, Cargo.toml
=> release: v0.12.2

src/proxy_cli.rs
The most common error I believe that is encountered is the `No such file or directory (os error 2)` when trying to execute a component from a toolchain which does not have the component installed. This is because fuelup tries to directly execute the executable from path, and if not found, it means that the file does not exist.
Here we handle `ErrorKind::NotFound` in a custom way to give the users more info on what happened in the context of fuelup and components.
=> feat: handle no such file error

Cargo.lock, Cargo.toml
=> release: v0.14.0

src/download.rs
realized while looking at logs from someone reporting errors on discord, it's hard to know for sure the error when it's ignored.
=> tweak: do not consume download Err

Cargo.lock, Cargo.toml
Adds support for `forc-index`, and other minor updates
=> release: v0.15.0

Cargo.lock, Cargo.toml
=> release: v0.15.1

src/ops/fuelup_default.rs, src/ops/fuelup_toolchain/install.rs, src/ops/fuelup_toolchain/uninstall.rs, src/ops/fuelup_update.rs, src/toolchain.rs
Discovered here: https://github.com/FuelLabs/fuelup/pull/317#discussion_r1065218363
=> refactor: update `Toolchain::from_path` to return `Self` instead of `Result<Self>`

Cargo.lock, Cargo.toml
=> release: bump v0.16.1

src/ops/fuelup_self.rs
closes #356 
We try to re-link `fuelup` to whatever components exist in `~/.fuelup/bin` at the time of `fuelup self update`.
To test:
1. checkout an older version of fuelup (v0.15 works).
2. build it and move it to replace the version in ~/.fuelup/bin
3. fuelup should not work with `fuel-toolchain.toml` now, you can confirm this by running `fuelup show` with an override in the CWD, and run `forc` (which should run your default `forc`)
4. now, checkout this branch, run `cargo run self update` which should re-link the components.
5. executing `forc` should now run what is in the override, and `fuelup show` shows your override.
=> relink fuelup to components to push updates

src/ops/fuelup_show.rs
=>  fix: fuelup show display string

Cargo.lock, Cargo.toml
=> release: v0.16.2

src/toolchain.rs
follow up to #372 
https://github.com/FuelLabs/fuelup/pull/372#discussion_r1090239654
Makes the `add_component()` function more readable. No logic changes beyond moving the code block out.
=> refactor: std lib caching in toolchain.rs

.github/workflows/test-toolchain-compatibility.yml
fixes this error: https://github.com/FuelLabs/fuelup/actions/runs/4130173462
=> bug(ci): add missing with

Cargo.lock, Cargo.toml
Various bug fixes:
Breaking change surrounding the usage of store:
New features:
=> release: 0.17.0

Cargo.lock, Cargo.toml
=> release: v0.17.1

src/channel.rs, src/commands/toolchain.rs, src/constants.rs, src/toolchain.rs, src/toolchain_override.rs
=> feat: beta-3 toolchain

Cargo.lock, Cargo.toml
=> release: v0.18.0

docs/src/developer_guide/building_a_channel.md, docs/src/developer_guide/index.md
followup to #392, since I missed out the comments and turned on auto-merge.
=> docs: improve `build-channel` docs

Cargo.lock, Cargo.toml
=> release: v0.18.1

README.md, docs/src/installation/index.md, src/ops/fuelup_self.rs
=> Update installation URLs

src/download.rs, src/ops/fuelup_toolchain/list_revisions.rs
a quick PR as a followup to a [comment](https://github.com/FuelLabs/fuelup/pull/410#discussion_r1127193719) made by @sdankel to properly support the option of using a http proxy when using fuelup.
=> feat: agent abstraction

Cargo.lock, Cargo.toml
Doing a MINOR version bump instead of PATCH (https://github.com/FuelLabs/fuelup/pull/424) because the changes since v0.18.1 include a new feature: https://github.com/FuelLabs/fuelup/pull/410
=> release: v0.19.0

docs/src/basics.md, docs/src/concepts/channels/index.md, docs/src/concepts/channels/latest.md, docs/src/concepts/channels/nightly.md, docs/src/concepts/how_fuelup_works.md, docs/src/concepts/index.md, docs/src/concepts/toolchains.md, docs/src/index.md, docs/src/installation/index.md, docs/src/installation/other.md, docs/src/overrides.md
Adds section comments to the documentation so that the devrel team can easily pull content from this book
=> add section comments for devrel

.github/workflows/ci.yml, .github/workflows/gh-pages-meta.yml, .github/workflows/gh-pages.yml, .github/workflows/index-versions.yml, .github/workflows/publish-nightly-channel.yml, .github/workflows/test-toolchain-compatibility.yml
a little cleanup in the CI to attribute commits to the bot.
=> chore: attribute commits to github-actions bot

docs/src/concepts/channels.md
waiting for @kayagokalp to publish the `beta-4-rc` channel first.
=> doc: add section for `beta-4-rc` channel

channel-fuel-beta-3.toml
- Final version 0.19.4 for indexer beta-3
=> chore: final indexer beta-3 release

Cargo.lock, Cargo.toml
=> chore: bump to v0.19.3

ci/build-channel/src/main.rs, component/src/lib.rs, components.toml, tests/show.rs
=> feat: support `fuel-core-keygen` binary

Cargo.lock, Cargo.toml
=> chore: bump to v0.19.4

docs/src/concepts/channels.md, src/channel.rs, src/constants.rs, src/toolchain.rs
Adds `beta-4` channel support to fuelup.
=> feat: add beta-4 support

.github/workflows/index-versions.yml
=> Revert "ci: use bigger image to run check-versions ci workflow"

channel-fuel-beta-4.toml
- Upgrades indexer beta-4 to 0.20.11
=> chore: update indexer beta-4 to 0.20.11

docs/src/developer_guide/adding_components.md
Related https://github.com/FuelLabs/fuelup/issues/508 https://github.com/FuelLabs/fuelup/issues/485
=> Add documentation about `--version`

component/src/lib.rs, components.toml, tests/check.rs, tests/show.rs
Removes fuel-indexer and forc-index from fuelup.
=> feat: remove indexer from fuelup

channel-fuel-testnet.toml
Testnet channel:
- forc v0.59
- fuel-core v0.26.0
=> release: add testnet channel toml file

src/constants.rs, tests/component.rs
Points latest toolchain to testnet.
=> feat: make latest toolchain point to testnet

docs/src/concepts/channels.md, src/commands/toolchain.rs, src/toolchain_override.rs
=> Add `beta-5` and `testnet` to the channels section of the book.

docs/src/concepts/channels.md
=> remove unnecessary markdown-link-check-disable flag

docs/src/concepts/channels.md, docs/src/developer_guide/contributing_to_fuelup.md, src/ops/fuelup_default.rs
This PR corrects several grammatical errors in the documentation and comments, improving readability and clarity. These changes enhance the overall quality of the project’s written content.
=> Docs improvements

channel-fuel-testnet.toml
```
cargo run -- channel-fuel-testnet.toml 2024-07-25 forc=0.62.0 forc-wallet=0.8.2 fuel-core=0.31.0 fuel-core-keygen=0.31.0
```
=> Update testnet channel for forc 0.62.0

.github/workflows/ci.yml, .github/workflows/nightly-cargo-audit.yml, .github/workflows/publish-nightly-channel.yml
The "Notify on failure" step was being skipped.
=> fix: gh action slack notification

docs/src/basics.md
This pull request contains changes to improve clarity, correctness and structure.
=> fix: typos in documentation files

components.toml, docs/src/installation/index.md, tests/show.rs, tests/testcfg/mod.rs
closes #715. Adds forc-node command to fuelup components list.
=> feat: add forc-node

Cargo.lock, Cargo.toml
since we also got #728 i guess we can cut a new release? cc @JoshuaBatty
=> chore: bump to v0.27.3

tests/testcfg/mod.rs
=> fix: unblock ci by pinning nightlies to 2025-05-26

.github/workflows/update-channel.yml
closes #743.
This pull request enhances the workflow for updating channels by dynamically generating more descriptive pull request titles based on the packages provided as inputs. It also updates the logic for handling existing pull requests to ensure both the title and description are updated.
Enhancements to pull request title generation:
* [`.github/workflows/update-channel.yml`](diffhunk://#diff-2b36e3fdc20feb042dd75ef02e47bfc426d509b17922068e1097a6e48d266b0fR147-R174): Added logic to build pull request titles dynamically based on the packages provided as inputs (`forc`, `forc-wallet`, `fuel-core`, `fuel-core-keygen`). If no packages are specified, a generic title is used.
Improved handling of existing pull requests:
* [`.github/workflows/update-channel.yml`](diffhunk://#diff-2b36e3fdc …
=> ci: improve PR descriptions for update-channel workflows

docs/src/concepts/channels.md, fuelup-init.sh
Hello Team, I fixed some typos and inaccuracies in docs.
=> docs: fix typos and inaccuracies
